In [1]:
import numpy as np

In [2]:
myarr = np.array([23,34,56,78])

In [3]:
myarr

array([23, 34, 56, 78])

In [4]:
type(myarr)

numpy.ndarray

In [5]:
arr = np.array([34,23,10,70],np.int8)

In [6]:
arr

array([34, 23, 10, 70], dtype=int8)

#Array creation: Conversion from other Python structures

In [7]:
listarray = np.array([[1,2,3],[0,3,1],[0,3,1]])

In [8]:
listarray

array([[1, 2, 3],
       [0, 3, 1],
       [0, 3, 1]])

In [9]:
listarray.dtype

dtype('int64')

In [10]:
listarray.shape

(3, 3)

In [11]:
listarray.size

9

In [12]:
np.array({23,45,67})

array({67, 45, 23}, dtype=object)

In [13]:
zeroes = np.zeros((2, 5))

In [14]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
rng = np.arange(20)

In [16]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
type(rng)

numpy.ndarray

In [18]:
lspace = np.linspace(1,5,12)

In [19]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [20]:
lspace = np.linspace(1,4,4)

In [21]:
lspace

array([1., 2., 3., 4.])

In [22]:
lspace = np.linspace(1,8,4)

In [23]:
lspace

array([1.        , 3.33333333, 5.66666667, 8.        ])

In [24]:
emp = np.empty((4,6))

In [25]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.60219442e-306, 1.06810336e-306, 1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306, 6.23057349e-307,
        1.02360935e-306, 1.69120416e-306, 1.78022342e-306],
       [6.23058028e-307, 1.06811422e-306, 9.45699680e-308,
        1.11258854e-306, 1.11261502e-306, 1.42410839e-306],
       [7.56597770e-307, 6.23059726e-307, 1.42419530e-306,
        1.78019490e-306, 1.69119330e-306, 2.56765117e-312]])

In [26]:
emp_like = np.empty_like(lspace)

In [27]:
emp_like

array([1.        , 3.33333333, 5.66666667, 8.        ])

In [28]:
ide = np.identity(45)

In [29]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [30]:
arr = np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr = arr.ravel()

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [35]:
arr.shape

(99,)

In [36]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [42]:
x

[[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [43]:
ar = np.array(x)

In [44]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [45]:
ar.sum(axis=0)

array([12,  8,  9])

In [46]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [47]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [48]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [49]:
ar.ndim

2

In [50]:
ar.size

9

In [51]:
ar.nbytes

72

In [58]:
one = np.array([1,3,4,634,2])
one

array([  1,   3,   4, 634,   2])

In [59]:
one.argmax()

np.int64(3)

In [60]:
one.argsort()

array([0, 4, 1, 2, 3])

In [61]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [62]:
ar.argmin()

np.int64(8)

In [64]:
ar.argmax()

np.int64(6)

In [65]:
ar.argmax(axis=1)  #returning the indices where elements are max in col

array([2, 2, 0])

In [66]:
ar.argmax(axis=0)

array([2, 1, 1])

In [67]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [68]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [69]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [70]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [73]:
ar2 = np.array([[1,2,1],[4,0,6],[15,2,0]])

In [74]:
ar2

array([[ 1,  2,  1],
       [ 4,  0,  6],
       [15,  2,  0]])

In [75]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [22,  3,  0]])

In [76]:
[34,56]+[78,90]   #doesn't support operation will extend the list

[34, 56, 78, 90]

In [77]:
ar*ar2

array([[  1,   4,   3],
       [ 16,   0,  36],
       [105,   2,   0]])

In [78]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [79]:
ar.sum()

np.int64(29)

In [80]:
ar.max()

np.int64(7)

In [81]:
ar.min()

np.int64(0)

In [82]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [83]:
type(np.where(ar>5))

tuple

In [84]:
np.count_nonzero(ar)

8

In [85]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [86]:
import sys

In [89]:
py_ar = [0,4,55,2]

In [90]:
np_ar = np.array(py_ar)

In [92]:
sys.getsizeof(1) * len(py_ar)

112

In [93]:
np_ar.itemsize*np_ar.size

32